### ISSUE TITLE
Init freezes

### ISSUE THREAD

**Issue by LukasJerabek** [Cryss76/vmcloak#4]
First of all, thanks for the fork and try to fix bugs. However whenever I try to follow the documentation my VM always throws critical error. I have got windows 10, where I create ubuntu virtual box on which I follow the documentation. Logs does not include anything useful at least to me... 

I have checked Enable Nested VT-x/AMD-V 

I wonder if that has ever happend to you as well? I dont know what to suggest to reproduce, because I just follow the documentation.

Btw does resulting VM pass pafish tests? Could you please try to run the pafish.exe inside resulting VM? https://github.com/a0rtega/pafish
In case it does not pass those tests, I would no try to make it work anymore and it would save me some time...

**Comment by LukasJerabek** [comment]
Well it was probably due to trying to run this inside nested VirtualBox and badly allocated memory...

**Comment by Cryss76** [comment]
> I wonder if that has ever happend to you as well? I dont know what to suggest to reproduce, because I just follow the documentation.

I've never tried vmcloak in a VM sry.

> Btw does resulting VM pass pafish tests? Could you please try to run the pafish.exe inside resulting VM? https://github.com/a0rtega/pafish

Will defenetly test it though there are more urgent issues with the tool i will be fixing first.
