### ISSUE TITLE
vmcloak initialization - vm network adapter

### ISSUE THREAD

**Issue by D3vil0p3r** [Cryss76/vmcloak#6]
Hello @Cryss76 I'm trying to package your vmcloak fork for some Linux distros. I'm testing, when I run
```
vmcloak -d init --win7x64 win7x64base --cpus 2 --ramsize 2048 vboxnet0
2024-10-04 14:52:53,797 vmcloak ERROR: Invalid adapter/bridge: Bridge IP 192.168.56.1 is not part of network 192.168.30.0/24
```
I created vboxnet0 by:
```
VBoxManage hostonlyif create
VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1
```
as reported in the docs. How can I solve it?

**Comment by Cryss76** [comment]
vmcloak does not support virtual box atm. Only qemu-kvm is supported.

Can you tell me where you found that in the docs?

**Comment by D3vil0p3r** [comment]
https://vmcloak.readthedocs.io/en/latest/vbox.html

Where I can find a similar docs for qemu-kvm?

**Comment by Cryss76** [comment]
Okay, does are really old. [Here](https://github.com/Cryss76/vmcloak?tab=readme-ov-file#docs) is how you can create the docs yourself and then just open the index.html with your browser.

**Comment by D3vil0p3r** [comment]
How should I create a network interface by CLI for qemu to be used in vmcloak?

**Comment by Cryss76** [comment]
take a look right [there](https://github.com/Cryss76/vmcloak/blob/main/docs/qemu.rst#networking-mandatory-steps). `sudo vmcloak-qemubridge qemubr0 192.168.30.1/24` is what you looking for.
